"""Configuration and constants for screenwrite."""

from .constants import (
    # Beat generation constants
    TARGET_MIN_DURATION,
    TARGET_MAX_DURATION,
    WORDS_PER_SECOND,
    
    # Encoding constants
    SUPPORTED_ENCODINGS,
    
    # File validation constants
    MIN_FILE_SIZE,
    MAX_FILE_SIZE,
    VALID_MARKDOWN_EXTENSIONS,
    
    # API validation constants
    MIN_API_KEY_LENGTH,
    MAX_API_KEY_LENGTH,
    
    # Disk space warning threshold
    LOW_DISK_SPACE_THRESHOLD,
    
    # Video generation constants
    DEFAULT_FRAMERATE,
    DEFAULT_VIDEO_WIDTH,
    DEFAULT_VIDEO_HEIGHT,
    
    # Timeout constants
    NETWORK_TIMEOUT,
    SUBPROCESS_TIMEOUT,
    
    # FCPXML generation constants
    MIN_FCPXML_FILE_SIZE,
    
    # Text truncation for logs
    BEAT_TEXT_TRUNCATION_LENGTH,

    # Keyword Generation Constants
    STOCK_KEYWORD_STOP_WORDS,
    VISUAL_PATTERNS,
    YOUTUBE_PHRASE_STOP_WORDS,
    TECHNICAL_PATTERNS,

    # B-roll result filtering constants
    TALKING_HEAD_TITLE_PATTERNS,
    BROLL_TITLE_BOOST_PATTERNS,
    TALKING_HEAD_PENALTY,
    BROLL_BOOST,
    MIN_YOUTUBE_DURATION,
    MAX_YOUTUBE_DURATION,

    # LLM query generation constants
    DEFAULT_GEMINI_MODEL,
    GEMINI_REQUEST_TIMEOUT,

    # Game b-roll skeleton constants
    CHAPTER_SOURCE_QUERY_TEMPLATES,
    CHAPTER_SEARCH_RESULTS_PER_QUERY,
    CHAPTER_MAX_SOURCE_VIDEOS,
    CHAPTER_MIN_CHAPTERS,
    CHAPTER_MIN_SOURCE_DURATION,
    CHAPTER_MATCH_THRESHOLD,
    CHAPTER_OFFSET_STEP_SECONDS,
    CHAPTER_WINDOW_MIN_SECONDS,
    CHAPTER_WINDOW_SLACK_SECONDS,
    GAME_CANDIDATES_PER_BEAT,
    FANDOM_API_URL,
    WIKI_REQUEST_TIMEOUT,
    STILL_IMAGE_EXTENSIONS,
)

__all__ = [
    'TARGET_MIN_DURATION',
    'TARGET_MAX_DURATION',
    'WORDS_PER_SECOND',
    'SUPPORTED_ENCODINGS',
    'MIN_FILE_SIZE',
    'MAX_FILE_SIZE',
    'VALID_MARKDOWN_EXTENSIONS',
    'MIN_API_KEY_LENGTH',
    'MAX_API_KEY_LENGTH',
    'LOW_DISK_SPACE_THRESHOLD',
    'DEFAULT_FRAMERATE',
    'DEFAULT_VIDEO_WIDTH',
    'DEFAULT_VIDEO_HEIGHT',
    'NETWORK_TIMEOUT',
    'SUBPROCESS_TIMEOUT',
    'MIN_FCPXML_FILE_SIZE',
    'BEAT_TEXT_TRUNCATION_LENGTH',
    'STOCK_KEYWORD_STOP_WORDS',
    'VISUAL_PATTERNS',
    'YOUTUBE_PHRASE_STOP_WORDS',
    'TECHNICAL_PATTERNS',
    'TALKING_HEAD_TITLE_PATTERNS',
    'BROLL_TITLE_BOOST_PATTERNS',
    'TALKING_HEAD_PENALTY',
    'BROLL_BOOST',
    'MIN_YOUTUBE_DURATION',
    'MAX_YOUTUBE_DURATION',
    'DEFAULT_GEMINI_MODEL',
    'GEMINI_REQUEST_TIMEOUT',
    'CHAPTER_SOURCE_QUERY_TEMPLATES',
    'CHAPTER_SEARCH_RESULTS_PER_QUERY',
    'CHAPTER_MAX_SOURCE_VIDEOS',
    'CHAPTER_MIN_CHAPTERS',
    'CHAPTER_MIN_SOURCE_DURATION',
    'CHAPTER_MATCH_THRESHOLD',
    'CHAPTER_OFFSET_STEP_SECONDS',
    'CHAPTER_WINDOW_MIN_SECONDS',
    'CHAPTER_WINDOW_SLACK_SECONDS',
    'GAME_CANDIDATES_PER_BEAT',
    'FANDOM_API_URL',
    'WIKI_REQUEST_TIMEOUT',
    'STILL_IMAGE_EXTENSIONS',
]
