"""Configuration and constants for screenwrite."""

from .constants import (
    # Beat generation constants
    TARGET_MIN_DURATION,
    TARGET_MAX_DURATION,
    WORDS_PER_SECOND,
    
    # Encoding constants
    SUPPORTED_ENCODINGS,
    
    # File validation constants
    MIN_FILE_SIZE,
    MAX_FILE_SIZE,
    VALID_MARKDOWN_EXTENSIONS,
    
    # API validation constants
    MIN_API_KEY_LENGTH,
    MAX_API_KEY_LENGTH,
    
    # Disk space warning threshold
    LOW_DISK_SPACE_THRESHOLD,
    
    # Video generation constants
    DEFAULT_FRAMERATE,
    DEFAULT_VIDEO_WIDTH,
    DEFAULT_VIDEO_HEIGHT,
    
    # Timeout constants
    NETWORK_TIMEOUT,
    SUBPROCESS_TIMEOUT,
    
    # FCPXML generation constants
    MIN_FCPXML_FILE_SIZE,
    
    # Text truncation for logs
    BEAT_TEXT_TRUNCATION_LENGTH,

    # Keyword Generation Constants
    STOCK_KEYWORD_STOP_WORDS,
    VISUAL_PATTERNS,
    YOUTUBE_PHRASE_STOP_WORDS,
    TECHNICAL_PATTERNS,

    # B-roll query & result filtering constants
    BROLL_QUERY_MODIFIERS,
    TALKING_HEAD_TITLE_PATTERNS,
    BROLL_TITLE_BOOST_PATTERNS,
    TALKING_HEAD_PENALTY,
    BROLL_BOOST,
    MIN_YOUTUBE_DURATION,
    MAX_YOUTUBE_DURATION,

    # LLM query generation constants
    DEFAULT_GEMINI_MODEL,
    GEMINI_REQUEST_TIMEOUT,
)

__all__ = [
    'TARGET_MIN_DURATION',
    'TARGET_MAX_DURATION',
    'WORDS_PER_SECOND',
    'SUPPORTED_ENCODINGS',
    'MIN_FILE_SIZE',
    'MAX_FILE_SIZE',
    'VALID_MARKDOWN_EXTENSIONS',
    'MIN_API_KEY_LENGTH',
    'MAX_API_KEY_LENGTH',
    'LOW_DISK_SPACE_THRESHOLD',
    'DEFAULT_FRAMERATE',
    'DEFAULT_VIDEO_WIDTH',
    'DEFAULT_VIDEO_HEIGHT',
    'NETWORK_TIMEOUT',
    'SUBPROCESS_TIMEOUT',
    'MIN_FCPXML_FILE_SIZE',
    'BEAT_TEXT_TRUNCATION_LENGTH',
    'STOCK_KEYWORD_STOP_WORDS',
    'VISUAL_PATTERNS',
    'YOUTUBE_PHRASE_STOP_WORDS',
    'TECHNICAL_PATTERNS',
    'BROLL_QUERY_MODIFIERS',
    'TALKING_HEAD_TITLE_PATTERNS',
    'BROLL_TITLE_BOOST_PATTERNS',
    'TALKING_HEAD_PENALTY',
    'BROLL_BOOST',
    'MIN_YOUTUBE_DURATION',
    'MAX_YOUTUBE_DURATION',
    'DEFAULT_GEMINI_MODEL',
    'GEMINI_REQUEST_TIMEOUT',
]
